# This workflow will create a GitHub release every time a tag is pushed
name: Create GitHub Release

on:
  push:
    branches: "*"
    # branches: [next]
    # tags:
    #   - "v2.*"
    #   - "v3.*"

  pull_request:
    branches: [main]


    on:
      push:
        branches: main

  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
  
      - run: npm ci

      - run: npm build

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"

  release:
    name: Release
    runs-on: ubuntu-latest

    permissions: 
      contents: write
      
    steps:
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # draft: false
          prerelease: true
          automatic_release_tag: "latest"
          title: "Production Build"
          files: "*"
